permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "JM Jones"
  description: |
    I'm JM; In some ways, I'm like every other graphic, user experience & interface designer. I'm passionate about solving problems, making clean designs and unlocking the potential of existing brand identities. But most people who know me will say that I'm just as passionate about fitness (powerlifting) as I am about design. Being active in the gym has influenced some of my work — I've also gotten used to designing for clients in the fitness industry. I design because I love taking an idea and making it a reality. Seeing that idea grow and interact with others is one of my favourite feelings in the world. (That and hitting a new deadlift max.)
  font_url: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800,900"
  font_url: "https://use.typekit.net/bis5ofn.css"
  colors:
  rationales:
    colors.primary: |
      Blue is the primary brand colour. It was chosen to represent my brand, and also, to add a feel of trust and calmness throughout the site.
    colors.secondary: |
      This gray was chosen as a more neutral tone which still allows the site to look clean and modern. It is also the secondary brand colour.
    colors.accent: |
      This colour was chosen for specifc section and actions such as the <mark> tag.
    typefaces.primary: |
      Open Sans was chosen for its accessibility and readability. It is also a font I use as a part of my brand, so using it here makes my brand more consistent.
    typefaces.secondary: |
      Proxima Nova was chosen to be used fo headings. Its a slightly bolder font that matches my brand well. It is also a very readable font which is ideal for websites.
