permalink: pretty

theme: jekyll_patternbot

patternbot:
  title: "JM Jones"
  description: |
    Graphic Designer, UX & UI Designer
  font_url: "https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800,900"
  font_url: "https://use.typekit.net/bis5ofn.css"
  colors:
    background:
    accent:
    patterns:
      brand.logos: "white"
      brand.colours: "white"
      typography.headings: "white"
  rationales:
    colors.primary: |
      A gold colour was chosen to represent a more high-end and classy mood. It sets the tone for the site, and contrasts well against darker colours.
    colors.secondary: |
      This gray was chosen as a more neutral tone which still allows the site to look clean and modern.
    colors.accent: |
      This colour was chosen mostly for the footer and body copy text, on whie sections.
    typefaces.primary: |
      Open Sans was chosen for its accessibility and readability. It is also a font I use as a part of my brand, so using it here makes my brand more consistent.
    typefaces.secondary: |
      Proxima Nova was chosen to be used fo headings. Its a slightly bolder font that matches my brand well. It is also a very readable font which is ideal for websites.
