title: "Buttons"
description:
  Buttons are used for a dramatic call to action.

patterns:
  basic:
    title: "Basic"
    description: |
      Basic button for navigation
    fields:
      - name: text
        type: string
        example: "contact me"
      - name: url
        type: url
        example: "/contact/"
  basic-blue:
    title: "Basic Blue"
    description: |
      The blue version of a basic button for navigation
    fields:
      - name: text
        type: string
        example: "view gallery"
      - name: url
        type: url
        example: "/gallery/"
  basic-white:
    title: "Basic White"
    description: |
      The blue version of a basic button for navigation; for dark backgrounds
    fields:
      - name: text
        type: string
        example: "view example"
      - name: url
        type: url
        example: "/anocate-app/"
