title: "Buttons"
description:
  Buttons are used for a dramatic call to action.

patterns:
  basic:
    title: "Basic"
    description: |
      Default to using the basic button
    fields:
      - name: text
        type: string
        example: "View Watches"
