title: "Header"
description:
  The primary site navigation, which also includes the brand logo.

patterns:
  header:
    title: "Header"
    description: |
      The primary navigation of the site. It has a dropshadow, and turns into a hamburger mun on smaller screen sizes.
