patterns:
  case-study-banner:
    title: "Case Study Banner"
    description: |
      The is to be used on the homepage for showcasing the products and any other section of the website that contains product showcasing.
    fields:
      - name: title
        type: string
        example: "Eagle's Nest"
        - name: category
          type: string
          example: "Branding, Logo Design"
      - name: image
        type: string
        example: "eagles-nest-banner.jpg"
